name: Coverage

on: [workflow_dispatch, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.x.x

      - name: Build
        run: dotnet build work.sln /p:ContinuousIntegrationBuild=true

      - name: Unittest and coverage
        run: dotnet test work.sln /p:CollectCoverage=true /p:Threshold=100 /p:ThresholdType=line